[phases.setup]
aptPkgs = ["libjpeg-dev", "zlib1g-dev"]

[start]
cmd = "cd back && python manage.py collectstatic --noinput && python manage.py migrate --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
