[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = ["cd back && pip install -r requirements.txt"]

[phases.build]
cmds = ["cd back && python manage.py collectstatic --noinput"]

[start]
cmd = "cd back && python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
