[project]
# Specify this is a Python project
language = "python"
app-root = "back"  # points to your Django backend folder

[phases.setup]
# Install Python 3.11 and pip
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "bash start.sh"
