[phases.setup]
aptPkgs = ["libjpeg-dev", "zlib1g-dev"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "mkdir -p back/staticfiles"
]

[phases.build]
cmds = [
  "cd back && python manage.py collectstatic --noinput --clear"
]

[start]
cmd = "cd back && python manage.py migrate --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
